### ISSUE TITLE
Doesnt work on my machine

### ISSUE THREAD

**Issue by sSt3lla** [ttrssreal/hello-world#1]
When I run the program it crashes with segfault

**Comment by ttrssreal** [comment]
What hardware are you running on?
If you actually read the docs, you'll see we support a wide range of machines and architectures,
The full list is as follows:
My Machine

Can you provide a backtrace?

**Comment by sSt3lla** [comment]
![image](https://github.com/ttrssreal/hello-world/assets/80804239/278c3ab2-33fd-40b1-aa20-f671044e8cf9)

**Comment by ttrssreal** [comment]
obviously just don't accessing 0x800000001490... fixed
